# Generated by Django 5.0.6 on 2024-05-27 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=50, verbose_name='Categorya')),
                ('name_ru', models.CharField(max_length=50, verbose_name='Категория')),
                ('name_en', models.CharField(max_length=50, verbose_name='Categorya')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='foods/')),
                ('name_uz', models.CharField(max_length=255, verbose_name='Taom nomi')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название блюда')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name of the dish')),
                ('price', models.IntegerField()),
                ('description_uz', models.TextField(verbose_name='Tavsifi')),
                ('description_ru', models.TextField(verbose_name='Описание')),
                ('description_en', models.TextField(verbose_name='Description')),
                ('shop_rating', models.PositiveBigIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.category')),
            ],
        ),
    ]
