# Generated by Django 5.0.6 on 2024-05-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name_en',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name of the dish'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name_ru',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name_uz',
            field=models.CharField(max_length=255, unique=True, verbose_name='Taom nomi'),
        ),
    ]
